### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/actividad-1-infografia-Luz1727-1#1]
[Infografia-LuzArleth.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Luz1727-1/files/14284967/Infografia-LuzArleth.pdf)

**Comment by Elisahadad** [comment]
19 / 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
